version: "3"

tasks:
  go:add-license-headers:
    desc: Add missing go license headers
    cmds:
      - go install github.com/google/addlicense@v1.2.0
      - addlicense -c "ARDUINO SA (http://www.arduino.cc/)" -f ./license_header.tpl $(find . -name "*.go" -type f -print0 | xargs -0)

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:cache-dep-licenses:
    desc: Cache dependency license metadata
    deps:
      - task: general:prepare-deps
    cmds:
      - |
          if
            ! which licensed \
            &>/dev/null
          then
            if [[ {{OS}} == "windows" ]]; then
              echo "Licensed does not have Windows support."
              echo "Please use Linux/macOS or download the dependencies cache from the GitHub Actions workflow artifact."
            else
              echo "licensed not found or not in PATH."
              echo "Please install: https://github.com/licensee/licensed#installation"
            fi
            exit 1
          fi
      - licensed cache

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:check-dep-licenses:
    desc: Check for unapproved dependency licenses
    deps:
      - task: general:cache-dep-licenses
    cmds:
      - licensed status

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-dependencies-task/Taskfile.yml
  general:prepare-deps:
    desc: Prepare project dependencies for license check
    # No preparation is needed for Go module-based projects.
