version: "3"

vars:
  GOLANGCI_LINT_VERSION: v2.4.0
  GOIMPORTS_VERSION: v0.29.0
  DPRINT_VERSION: 0.48.0

tasks:
  init:
    desc: Setup local env
    deps:
      - install:linter
      - install:goimports
      - install:dprint

  install:linter:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b .bin/ {{ .GOLANGCI_LINT_VERSION }}

  install:goimports:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@{{ .GOIMPORTS_VERSION }}

  install:dprint:
    cmds:
      - curl -fsSL https://dprint.dev/install.sh | sh -s {{ .DPRINT_VERSION }}
      - mkdir -p .bin && cp $HOME/.dprint/bin/dprint .bin/dprint # workaround for local install

  go:add-license-headers:
    desc: Add missing go license headers
    cmds:
      - go install github.com/google/addlicense@v1.2.0
      - addlicense -c "ARDUINO SA (http://www.arduino.cc/)" -f ./license_header.tpl $(find . -name "*.go" -type f -print0 | xargs -0)

  test:
    desc: Run go tests
    cmds:
      - go test ./... -v -race {{ .CLI_ARGS }}

  lint:
    desc: Run the linters
    cmds:
      - ${PWD}/.bin/golangci-lint run --fix -v --timeout 300s {{ .CLI_ARGS }}

  fmt:
    desc: Run format
    cmds:
      - goimports -l -w .
      - ${PWD}/.bin/dprint fmt

  fmt-check:
    desc: Check format
    cmds:
      - ${PWD}/.bin/dprint check

  release:
    desc: Create a tag on the current commit and push it to the remote to trigger the release github workflow
    cmds:
      - |
          if [ -z "{{.CLI_ARGS}}" ]; then
            echo "Error: Version argument is required. Usage: task release -- <version>"
            exit 1
          fi
      - git tag -a "{{.CLI_ARGS}}" -m "Release {{.CLI_ARGS}}"
      - git push origin "{{.CLI_ARGS}}"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:cache-dep-licenses:
    desc: Cache dependency license metadata
    deps:
      - task: general:prepare-deps
    cmds:
      - |
          if
            ! which licensed \
            &>/dev/null
          then
            if [[ {{OS}} == "windows" ]]; then
              echo "Licensed does not have Windows support."
              echo "Please use Linux/macOS or download the dependencies cache from the GitHub Actions workflow artifact."
            else
              echo "licensed not found or not in PATH."
              echo "Please install: https://github.com/licensee/licensed#installation"
            fi
            exit 1
          fi
      - licensed cache

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:check-dep-licenses:
    desc: Check for unapproved dependency licenses
    deps:
      - task: general:cache-dep-licenses
    cmds:
      - licensed status

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-dependencies-task/Taskfile.yml
  general:prepare-deps:
    desc: Prepare project dependencies for license check
    # No preparation is needed for Go module-based projects.
